### ISSUE TITLE
return more correct and meaningful errors

### ISSUE THREAD

**Issue by yonatandt** [meateam/api-gateway#188] opened 2020-11-08 09:23 UTC
Error codes should match the error that occured.

__Internal Errors (5XX)__ - should return a generic message.
__Client Errors (4XX)__ - should return a more specific message so the client will know what the fault was and how to fix it.

Ensure that all of the errors are logged in detail with traceID and relevant values.

**Comment by Shahar-Y** [comment] 2020-11-24 07:54
duplicate of #144

**Closed by Shahar-Y** 2020-11-24 07:54 UTC
